import type { IconType } from "react-icons";
import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiC,
  SiCplusplus,
  SiHtml5,
  SiCss3,
  SiNodedotjs,
  SiExpress,
  SiReact,
  SiNextdotjs,
  SiBootstrap,
  SiChakraui,
  SiMongodb,
  SiMysql,
  SiPostgresql,
  SiRedis,
  SiFirebase,
  SiGit,
  SiPostman,
  SiNginx,
  SiRender,
  SiVercel,
  SiNetlify,
  SiFastapi,
  SiGooglebigquery,
} from "react-icons/si";
import { FaJava, FaAws, FaDatabase, FaTheaterMasks } from "react-icons/fa";
import { VscCode } from "react-icons/vsc";

// Maps each skill label to its brand icon + colour. Icons that are
// effectively white/black on their own get a light tint so they stay
// visible on the dark cosmic background.
export const SKILL_ICONS: Record<string, { Icon: IconType; color: string }> = {
  JavaScript: { Icon: SiJavascript, color: "#f7df1e" },
  TypeScript: { Icon: SiTypescript, color: "#3178c6" },
  Java: { Icon: FaJava, color: "#f89820" },
  Python: { Icon: SiPython, color: "#3776ab" },
  C: { Icon: SiC, color: "#a8b9cc" },
  "C++": { Icon: SiCplusplus, color: "#00599c" },
  HTML: { Icon: SiHtml5, color: "#e34f26" },
  CSS: { Icon: SiCss3, color: "#1572b6" },
  SQL: { Icon: FaDatabase, color: "#dbb028" },
  NodeJS: { Icon: SiNodedotjs, color: "#5fa04e" },
  ExpressJS: { Icon: SiExpress, color: "#cbd5e1" },
  FastAPI: { Icon: SiFastapi, color: "#009688" },
  ReactJS: { Icon: SiReact, color: "#61dafb" },
  NextJS: { Icon: SiNextdotjs, color: "#e5e7eb" },
  Bootstrap: { Icon: SiBootstrap, color: "#7952b3" },
  "Chakra UI": { Icon: SiChakraui, color: "#319795" },
  MongoDB: { Icon: SiMongodb, color: "#47a248" },
  MySQL: { Icon: SiMysql, color: "#4479a1" },
  PostgreSQL: { Icon: SiPostgresql, color: "#4169e1" },
  Redis: { Icon: SiRedis, color: "#ff4438" },
  Firebase: { Icon: SiFirebase, color: "#ffca28" },
  BigQuery: { Icon: SiGooglebigquery, color: "#669df6" },
  Git: { Icon: SiGit, color: "#f05032" },
  Postman: { Icon: SiPostman, color: "#ff6c37" },
  Playwright: { Icon: FaTheaterMasks, color: "#2ead33" },
  AWS: { Icon: FaAws, color: "#ff9900" },
  Nginx: { Icon: SiNginx, color: "#009639" },
  "VS Code": { Icon: VscCode, color: "#3b9eff" },
  Render: { Icon: SiRender, color: "#e5e7eb" },
  Vercel: { Icon: SiVercel, color: "#e5e7eb" },
  Netlify: { Icon: SiNetlify, color: "#00c7b7" },
};
